### ISSUE TITLE
Bevy 0.12

### ISSUE THREAD

**Issue by SebMenozzi** [Ria8651/grid-hierarchy#4]
Hey Brian,

Started forking your project and bumping to the newest bevy version 0.12 => https://github.com/SebMenozzi/bevy-voxel-engine, still WIP tho.
Also tried to find your email to reach out to you but didn't find any haha, got some ideas I would like to discuss.
If you have some time (email on my profile) :)

Cheers

**Comment by ria8651** [comment]
Hello, thanks for the interest :)

I probably won't work on this project any more as I'm focusing on https://github.com/ria8651/alex but I'm happy to chat. My discord is `bink_studios`.
